'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("APKInstaller.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to abort installing the current APK? The currently installing package will probably be unusable if you chose to abort..
        '''</summary>
        Friend Shared ReadOnly Property abortCurrentApk() As String
            Get
                Return ResourceManager.GetString("abortCurrentApk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADB exited with error code.
        '''</summary>
        Friend Shared ReadOnly Property adbExitErrorCode() As String
            Get
                Return ResourceManager.GetString("adbExitErrorCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APK.
        '''</summary>
        Friend Shared ReadOnly Property apk() As String
            Get
                Return ResourceManager.GetString("apk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APK Install Finished.
        '''</summary>
        Friend Shared ReadOnly Property apkInstallFinished() As String
            Get
                Return ResourceManager.GetString("apkInstallFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to APKs.
        '''</summary>
        Friend Shared ReadOnly Property apks() As String
            Get
                Return ResourceManager.GetString("apks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An application error has been encountered..
        '''</summary>
        Friend Shared ReadOnly Property appError() As String
            Get
                Return ResourceManager.GetString("appError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following file may be wanted by troubleshooters and/or ninja monkeys:.
        '''</summary>
        Friend Shared ReadOnly Property appErrorFileWanted() As String
            Get
                Return ResourceManager.GetString("appErrorFileWanted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Built by .
        '''</summary>
        Friend Shared ReadOnly Property Built_by() As String
            Get
                Return ResourceManager.GetString("Built_by", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking device(s)...This may be a moment or two.
        '''</summary>
        Friend Shared ReadOnly Property checkDevices() As String
            Get
                Return ResourceManager.GetString("checkDevices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm.
        '''</summary>
        Friend Shared ReadOnly Property Confirm() As String
            Get
                Return ResourceManager.GetString("Confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to correct those configuration issues?.
        '''</summary>
        Friend Shared ReadOnly Property correctConfigIssue() As String
            Get
                Return ResourceManager.GetString("correctConfigIssue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is the device &quot;.
        '''</summary>
        Friend Shared ReadOnly Property correctDevice1() As String
            Get
                Return ResourceManager.GetString("correctDevice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot; correct?.
        '''</summary>
        Friend Shared ReadOnly Property correctDevice2() As String
            Get
                Return ResourceManager.GetString("correctDevice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Details: .
        '''</summary>
        Friend Shared ReadOnly Property details() As String
            Get
                Return ResourceManager.GetString("details", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done!.
        '''</summary>
        Friend Shared ReadOnly Property done() As String
            Get
                Return ResourceManager.GetString("done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drag an APK file here....
        '''</summary>
        Friend Shared ReadOnly Property dragFile() As String
            Get
                Return ResourceManager.GetString("dragFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failure! .
        '''</summary>
        Friend Shared ReadOnly Property failure() As String
            Get
                Return ResourceManager.GetString("failure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oops, it looks like at least one your APK files can&apos;t be installed.
        '''</summary>
        Friend Shared ReadOnly Property fileCanNotBeInstalled() As String
            Get
                Return ResourceManager.GetString("fileCanNotBeInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to doesn&apos;t seem to exist at this moment. You may want to try that file again in a moment or two..
        '''</summary>
        Friend Shared ReadOnly Property fileDoesNotExist() As String
            Get
                Return ResourceManager.GetString("fileDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to the FIRST App Installer! Try dragging an APK file onto me to install or use the Browse button below..
        '''</summary>
        Friend Shared ReadOnly Property firstRunMessage() As String
            Get
                Return ResourceManager.GetString("firstRunMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you really, absolutely sure you want to force the installation by any means necessary? This WILL be destructive if the app is currently installed on the phone.&quot;.
        '''</summary>
        Friend Shared ReadOnly Property forceConfirm() As String
            Get
                Return ResourceManager.GetString("forceConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to forcefully remove any existing package to prep for a clean re-installation?.
        '''</summary>
        Friend Shared ReadOnly Property forceQuestion() As String
            Get
                Return ResourceManager.GetString("forceQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  did not complete successfully..
        '''</summary>
        Friend Shared ReadOnly Property hasFinishedError() As String
            Get
                Return ResourceManager.GetString("hasFinishedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  has finished successfully!.
        '''</summary>
        Friend Shared ReadOnly Property hasFinishedSucess() As String
            Get
                Return ResourceManager.GetString("hasFinishedSucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The install has been aborted.
        '''</summary>
        Friend Shared ReadOnly Property installAborted() As String
            Get
                Return ResourceManager.GetString("installAborted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am going to install the APK in the location .
        '''</summary>
        Friend Shared ReadOnly Property installApkAtConfirm() As String
            Get
                Return ResourceManager.GetString("installApkAtConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The installation of the .
        '''</summary>
        Friend Shared ReadOnly Property installationOf() As String
            Get
                Return ResourceManager.GetString("installationOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installing.
        '''</summary>
        Friend Shared ReadOnly Property installing() As String
            Get
                Return ResourceManager.GetString("installing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Android SDK is not completely correctly configured at this moment..
        '''</summary>
        Friend Shared ReadOnly Property invalidAndroidSdkConfig() As String
            Get
                Return ResourceManager.GetString("invalidAndroidSdkConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is not a valid Android app. Please verify that the file ends with &quot;.APK&quot;..
        '''</summary>
        Friend Shared ReadOnly Property invalidApk() As String
            Get
                Return ResourceManager.GetString("invalidApk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid SDK defined, when valid SDK can be found.
        '''</summary>
        Friend Shared ReadOnly Property invalidSdkDefinedValidPresent() As String
            Get
                Return ResourceManager.GetString("invalidSdkDefinedValidPresent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is a directory. Unfortunately, this app can&apos;t handle installing directories, for now..
        '''</summary>
        Friend Shared ReadOnly Property isDirError() As String
            Get
                Return ResourceManager.GetString("isDirError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify.
        '''</summary>
        Friend Shared ReadOnly Property Modify() As String
            Get
                Return ResourceManager.GetString("Modify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot; onto the device &quot;.
        '''</summary>
        Friend Shared ReadOnly Property onto_the_device() As String
            Get
                Return ResourceManager.GetString("onto_the_device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Android App Packages (*.apk)|*.apk|All Files|*.*.
        '''</summary>
        Friend Shared ReadOnly Property openFileDialogFilter() As String
            Get
                Return ResourceManager.GetString("openFileDialogFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Android APK files.
        '''</summary>
        Friend Shared ReadOnly Property openFileDialogTitle() As String
            Get
                Return ResourceManager.GetString("openFileDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are other APK files to install. Do you want to keep them and add this to install?.
        '''</summary>
        Friend Shared ReadOnly Property otherApkFiles() As String
            Get
                Return ResourceManager.GetString("otherApkFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready to install? Click Install. If not, you can drag and drop some more files.
        '''</summary>
        Friend Shared ReadOnly Property readyToInstall() As String
            Get
                Return ResourceManager.GetString("readyToInstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Want to install another app or install on a different device?.
        '''</summary>
        Friend Shared ReadOnly Property readyToInstallBatch() As String
            Get
                Return ResourceManager.GetString("readyToInstallBatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrying package in .
        '''</summary>
        Friend Shared ReadOnly Property retryIn() As String
            Get
                Return ResourceManager.GetString("retryIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retrying the install of.
        '''</summary>
        Friend Shared ReadOnly Property retrying_install() As String
            Get
                Return ResourceManager.GetString("retrying_install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to second.
        '''</summary>
        Friend Shared ReadOnly Property second() As String
            Get
                Return ResourceManager.GetString("second", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to seconds.
        '''</summary>
        Friend Shared ReadOnly Property seconds() As String
            Get
                Return ResourceManager.GetString("seconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting Installs....
        '''</summary>
        Friend Shared ReadOnly Property startingInstalls() As String
            Get
                Return ResourceManager.GetString("startingInstalls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Android device can&apos;t be found in a reasonable amount of time..
        '''</summary>
        Friend Shared ReadOnly Property timeoutWaiting() As String
            Get
                Return ResourceManager.GetString("timeoutWaiting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The installation of &quot;.
        '''</summary>
        Friend Shared ReadOnly Property unsuccessfulInstall1() As String
            Get
                Return ResourceManager.GetString("unsuccessfulInstall1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot; did not succeed..
        '''</summary>
        Friend Shared ReadOnly Property unsuccessfulInstall2() As String
            Get
                Return ResourceManager.GetString("unsuccessfulInstall2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to update the installed package on the phone?.
        '''</summary>
        Friend Shared ReadOnly Property updateQuestion() As String
            Get
                Return ResourceManager.GetString("updateQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Ready! Click to restart whenever you are ready.
        '''</summary>
        Friend Shared ReadOnly Property updateReady() As String
            Get
                Return ResourceManager.GetString("updateReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Make sure the device that want to use is connected, uses Android,.
        '''</summary>
        Friend Shared ReadOnly Property userTroubleshootingA1() As String
            Get
                Return ResourceManager.GetString("userTroubleshootingA1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to has Developer Options enabled, and the device is in Debug mode..
        '''</summary>
        Friend Shared ReadOnly Property userTroubleshootingA2() As String
            Get
                Return ResourceManager.GetString("userTroubleshootingA2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for device..
        '''</summary>
        Friend Shared ReadOnly Property waitForDevice1() As String
            Get
                Return ResourceManager.GetString("waitForDevice1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for device...
        '''</summary>
        Friend Shared ReadOnly Property waitForDevice2() As String
            Get
                Return ResourceManager.GetString("waitForDevice2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for device....
        '''</summary>
        Friend Shared ReadOnly Property waitForDevice3() As String
            Get
                Return ResourceManager.GetString("waitForDevice3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to restart the app?.
        '''</summary>
        Friend Shared ReadOnly Property wantToRestart() As String
            Get
                Return ResourceManager.GetString("wantToRestart", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
