// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace APKInstaller.i18n {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("APKInstaller.i18n.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        public static string invalidAndroidSdkConfig {
            get {
                return ResourceManager.GetString("invalidAndroidSdkConfig", resourceCulture);
            }
        }
        
        public static string wantToRestart {
            get {
                return ResourceManager.GetString("wantToRestart", resourceCulture);
            }
        }
        
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        public static string unsuccessfulInstall2 {
            get {
                return ResourceManager.GetString("unsuccessfulInstall2", resourceCulture);
            }
        }
        
        public static string unsuccessfulInstall1 {
            get {
                return ResourceManager.GetString("unsuccessfulInstall1", resourceCulture);
            }
        }
        
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        public static string startingInstalls {
            get {
                return ResourceManager.GetString("startingInstalls", resourceCulture);
            }
        }
        
        public static string fileCanNotBeInstalled {
            get {
                return ResourceManager.GetString("fileCanNotBeInstalled", resourceCulture);
            }
        }
        
        public static string userTroubleshootingA1 {
            get {
                return ResourceManager.GetString("userTroubleshootingA1", resourceCulture);
            }
        }
        
        public static string userTroubleshootingA2 {
            get {
                return ResourceManager.GetString("userTroubleshootingA2", resourceCulture);
            }
        }
        
        public static string onto_the_device {
            get {
                return ResourceManager.GetString("onto_the_device", resourceCulture);
            }
        }
        
        public static string forceConfirm {
            get {
                return ResourceManager.GetString("forceConfirm", resourceCulture);
            }
        }
        
        public static string fileDoesNotExist {
            get {
                return ResourceManager.GetString("fileDoesNotExist", resourceCulture);
            }
        }
        
        public static string retrying_install {
            get {
                return ResourceManager.GetString("retrying_install", resourceCulture);
            }
        }
        
        public static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        public static string invalidApk {
            get {
                return ResourceManager.GetString("invalidApk", resourceCulture);
            }
        }
        
        public static string installationOf {
            get {
                return ResourceManager.GetString("installationOf", resourceCulture);
            }
        }
        
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        public static string waitForDevice1 {
            get {
                return ResourceManager.GetString("waitForDevice1", resourceCulture);
            }
        }
        
        public static string waitForDevice3 {
            get {
                return ResourceManager.GetString("waitForDevice3", resourceCulture);
            }
        }
        
        public static string waitForDevice2 {
            get {
                return ResourceManager.GetString("waitForDevice2", resourceCulture);
            }
        }
        
        public static string isDirError {
            get {
                return ResourceManager.GetString("isDirError", resourceCulture);
            }
        }
        
        public static string readyToInstall {
            get {
                return ResourceManager.GetString("readyToInstall", resourceCulture);
            }
        }
        
        public static string updateQuestion {
            get {
                return ResourceManager.GetString("updateQuestion", resourceCulture);
            }
        }
        
        public static string dragFile {
            get {
                return ResourceManager.GetString("dragFile", resourceCulture);
            }
        }
        
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        public static string readyToInstallBatch {
            get {
                return ResourceManager.GetString("readyToInstallBatch", resourceCulture);
            }
        }
        
        public static string apk {
            get {
                return ResourceManager.GetString("apk", resourceCulture);
            }
        }
        
        public static string checkDevices {
            get {
                return ResourceManager.GetString("checkDevices", resourceCulture);
            }
        }
        
        public static string updateReady {
            get {
                return ResourceManager.GetString("updateReady", resourceCulture);
            }
        }
        
        public static string invalidSdkDefinedValidPresent {
            get {
                return ResourceManager.GetString("invalidSdkDefinedValidPresent", resourceCulture);
            }
        }
        
        public static string installing {
            get {
                return ResourceManager.GetString("installing", resourceCulture);
            }
        }
        
        public static string forceQuestion {
            get {
                return ResourceManager.GetString("forceQuestion", resourceCulture);
            }
        }
        
        public static string otherApkFiles {
            get {
                return ResourceManager.GetString("otherApkFiles", resourceCulture);
            }
        }
        
        public static string adbExitErrorCode {
            get {
                return ResourceManager.GetString("adbExitErrorCode", resourceCulture);
            }
        }
        
        public static string appErrorFileWanted {
            get {
                return ResourceManager.GetString("appErrorFileWanted", resourceCulture);
            }
        }
        
        public static string correctConfigIssue {
            get {
                return ResourceManager.GetString("correctConfigIssue", resourceCulture);
            }
        }
        
        public static string Built_by {
            get {
                return ResourceManager.GetString("Built_by", resourceCulture);
            }
        }
        
        public static string hasFinishedError {
            get {
                return ResourceManager.GetString("hasFinishedError", resourceCulture);
            }
        }
        
        public static string correctDevice2 {
            get {
                return ResourceManager.GetString("correctDevice2", resourceCulture);
            }
        }
        
        public static string correctDevice1 {
            get {
                return ResourceManager.GetString("correctDevice1", resourceCulture);
            }
        }
        
        public static string retryIn {
            get {
                return ResourceManager.GetString("retryIn", resourceCulture);
            }
        }
        
        public static string installApkAtConfirm {
            get {
                return ResourceManager.GetString("installApkAtConfirm", resourceCulture);
            }
        }
        
        public static string installAborted {
            get {
                return ResourceManager.GetString("installAborted", resourceCulture);
            }
        }
        
        public static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        public static string firstRunMessage {
            get {
                return ResourceManager.GetString("firstRunMessage", resourceCulture);
            }
        }
        
        public static string timeoutWaiting {
            get {
                return ResourceManager.GetString("timeoutWaiting", resourceCulture);
            }
        }
        
        public static string openFileDialogTitle {
            get {
                return ResourceManager.GetString("openFileDialogTitle", resourceCulture);
            }
        }
        
        public static string abortCurrentApk {
            get {
                return ResourceManager.GetString("abortCurrentApk", resourceCulture);
            }
        }
        
        public static string apkInstallFinished {
            get {
                return ResourceManager.GetString("apkInstallFinished", resourceCulture);
            }
        }
        
        public static string appError {
            get {
                return ResourceManager.GetString("appError", resourceCulture);
            }
        }
        
        public static string hasFinishedSucess {
            get {
                return ResourceManager.GetString("hasFinishedSucess", resourceCulture);
            }
        }
        
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        public static string apks {
            get {
                return ResourceManager.GetString("apks", resourceCulture);
            }
        }
    }
}
