//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APKInstaller.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APKInstaller.i18n.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to abort installing the current APK? The currently installing package will probably be unusable if you chose to abort..
        /// </summary>
        public static string abortCurrentApk {
            get {
                return ResourceManager.GetString("abortCurrentApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB exited with error code.
        /// </summary>
        public static string adbExitErrorCode {
            get {
                return ResourceManager.GetString("adbExitErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK.
        /// </summary>
        public static string apk {
            get {
                return ResourceManager.GetString("apk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Install Finished.
        /// </summary>
        public static string apkInstallFinished {
            get {
                return ResourceManager.GetString("apkInstallFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APKs.
        /// </summary>
        public static string apks {
            get {
                return ResourceManager.GetString("apks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error has been encountered..
        /// </summary>
        public static string appError {
            get {
                return ResourceManager.GetString("appError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file may be wanted by troubleshooters and/or ninja monkeys:.
        /// </summary>
        public static string appErrorFileWanted {
            get {
                return ResourceManager.GetString("appErrorFileWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built by .
        /// </summary>
        public static string Built_by {
            get {
                return ResourceManager.GetString("Built_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking device(s)...This may be a moment or two.
        /// </summary>
        public static string checkDevices {
            get {
                return ResourceManager.GetString("checkDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to correct those configuration issues?.
        /// </summary>
        public static string correctConfigIssue {
            get {
                return ResourceManager.GetString("correctConfigIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the device &quot;.
        /// </summary>
        public static string correctDevice1 {
            get {
                return ResourceManager.GetString("correctDevice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; correct?.
        /// </summary>
        public static string correctDevice2 {
            get {
                return ResourceManager.GetString("correctDevice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details: .
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag an APK file here....
        /// </summary>
        public static string dragFile {
            get {
                return ResourceManager.GetString("dragFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure! .
        /// </summary>
        public static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, it looks like at least one your APK files can&apos;t be installed.
        /// </summary>
        public static string fileCanNotBeInstalled {
            get {
                return ResourceManager.GetString("fileCanNotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doesn&apos;t seem to exist at this moment. You may want to try that file again in a moment or two..
        /// </summary>
        public static string fileDoesNotExist {
            get {
                return ResourceManager.GetString("fileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the FIRST App Installer! Try dragging an APK file onto me to install or use the Browse button below..
        /// </summary>
        public static string firstRunMessage {
            get {
                return ResourceManager.GetString("firstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you really, absolutely sure you want to force the installation by any means necessary? This WILL be destructive if the app is currently installed on the phone.&quot;.
        /// </summary>
        public static string forceConfirm {
            get {
                return ResourceManager.GetString("forceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to forcefully remove any existing package to prep for a clean re-installation?.
        /// </summary>
        public static string forceQuestion {
            get {
                return ResourceManager.GetString("forceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  did not complete successfully..
        /// </summary>
        public static string hasFinishedError {
            get {
                return ResourceManager.GetString("hasFinishedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has finished successfully!.
        /// </summary>
        public static string hasFinishedSucess {
            get {
                return ResourceManager.GetString("hasFinishedSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The install has been aborted.
        /// </summary>
        public static string installAborted {
            get {
                return ResourceManager.GetString("installAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am going to install the APK in the location .
        /// </summary>
        public static string installApkAtConfirm {
            get {
                return ResourceManager.GetString("installApkAtConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of the .
        /// </summary>
        public static string installationOf {
            get {
                return ResourceManager.GetString("installationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string installing {
            get {
                return ResourceManager.GetString("installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android SDK is not completely correctly configured at this moment..
        /// </summary>
        public static string invalidAndroidSdkConfig {
            get {
                return ResourceManager.GetString("invalidAndroidSdkConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid Android app. Please verify that the file ends with &quot;.APK&quot;..
        /// </summary>
        public static string invalidApk {
            get {
                return ResourceManager.GetString("invalidApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SDK defined, when valid SDK can be found.
        /// </summary>
        public static string invalidSdkDefinedValidPresent {
            get {
                return ResourceManager.GetString("invalidSdkDefinedValidPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a directory. Unfortunately, this app can&apos;t handle installing directories, for now..
        /// </summary>
        public static string isDirError {
            get {
                return ResourceManager.GetString("isDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; onto the device &quot;.
        /// </summary>
        public static string onto_the_device {
            get {
                return ResourceManager.GetString("onto_the_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android App Packages (*.apk)|*.apk|All Files|*.*.
        /// </summary>
        public static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Android APK files.
        /// </summary>
        public static string openFileDialogTitle {
            get {
                return ResourceManager.GetString("openFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are other APK files to install. Do you want to keep them and add this to install?.
        /// </summary>
        public static string otherApkFiles {
            get {
                return ResourceManager.GetString("otherApkFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install? Click Install. If not, you can drag and drop some more files.
        /// </summary>
        public static string readyToInstall {
            get {
                return ResourceManager.GetString("readyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to install another app or install on a different device?.
        /// </summary>
        public static string readyToInstallBatch {
            get {
                return ResourceManager.GetString("readyToInstallBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying package in .
        /// </summary>
        public static string retryIn {
            get {
                return ResourceManager.GetString("retryIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying the install of.
        /// </summary>
        public static string retrying_install {
            get {
                return ResourceManager.GetString("retrying_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Installs....
        /// </summary>
        public static string startingInstalls {
            get {
                return ResourceManager.GetString("startingInstalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android device can&apos;t be found in a reasonable amount of time..
        /// </summary>
        public static string timeoutWaiting {
            get {
                return ResourceManager.GetString("timeoutWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation of &quot;.
        /// </summary>
        public static string unsuccessfulInstall1 {
            get {
                return ResourceManager.GetString("unsuccessfulInstall1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; did not succeed..
        /// </summary>
        public static string unsuccessfulInstall2 {
            get {
                return ResourceManager.GetString("unsuccessfulInstall2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update the installed package on the phone?.
        /// </summary>
        public static string updateQuestion {
            get {
                return ResourceManager.GetString("updateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Ready! Click to restart whenever you are ready.
        /// </summary>
        public static string updateReady {
            get {
                return ResourceManager.GetString("updateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the device that want to use is connected, uses Android,.
        /// </summary>
        public static string userTroubleshootingA1 {
            get {
                return ResourceManager.GetString("userTroubleshootingA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has Developer Options enabled, and the device is in Debug mode..
        /// </summary>
        public static string userTroubleshootingA2 {
            get {
                return ResourceManager.GetString("userTroubleshootingA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device..
        /// </summary>
        public static string waitForDevice1 {
            get {
                return ResourceManager.GetString("waitForDevice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device...
        /// </summary>
        public static string waitForDevice2 {
            get {
                return ResourceManager.GetString("waitForDevice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device....
        /// </summary>
        public static string waitForDevice3 {
            get {
                return ResourceManager.GetString("waitForDevice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart the app?.
        /// </summary>
        public static string wantToRestart {
            get {
                return ResourceManager.GetString("wantToRestart", resourceCulture);
            }
        }
    }
}
